In [1]:
import copy
import numpy as np
import pandas as pd

In [2]:
data_pre = pd.read_excel('./data.xlsx')
labels = data_pre.keys()[1:]
names = data_pre['银行']
values = data_pre[labels].values

In [3]:
values

array([[ 0.483 , 13.2682,  0.    ,  4.3646,  5.107 ],
       [ 0.4035, 13.4909, 39.0131,  3.6151,  5.5005],
       [ 0.8979, 25.7776,  9.0513,  4.892 ,  7.5342],
       [ 0.5927, 16.0245, 13.2935,  4.4529,  6.5913]])

In [4]:
# 正向化 & 标准化
for i in range(len(labels)):
    temp = values[:, i]
    max_values = np.max(temp)
    min_values = np.min(temp)
    if i is 2:
        values[:, i] = (max_values - temp)/(max_values - min_values)
    else:
        values[:, i] = (temp - min_values)/(max_values - min_values)

In [5]:
# 信息承载量计算
# 对比性
thegma = values.std(axis=0)
# 矛盾性 -> 计算皮尔逊相关系数
r_pearson = np.corrcoef(values.T)

In [6]:
r_pearson

array([[1.        , 0.97898823, 0.43347316, 0.87878149, 0.92378756],
       [0.97898823, 1.        , 0.2672594 , 0.76741534, 0.92090278],
       [0.43347316, 0.2672594 , 1.        , 0.79834444, 0.1630603 ],
       [0.87878149, 0.76741534, 0.79834444, 1.        , 0.72171726],
       [0.92378756, 0.92090278, 0.1630603 , 0.72171726, 1.        ]])

In [7]:
thegma

array([0.3797096 , 0.40792698, 0.37133117, 0.35957058, 0.39172437])

In [8]:
f_pearson = (1 - r_pearson).sum(axis=0)

In [9]:
# 信息承载量
c = thegma * f_pearson

In [10]:
w = c/c.sum()

In [11]:
# 得分
score = values @ w

In [12]:
Score = 100 * score/np.max(score)

In [13]:
Score

array([ 49.70763423,   4.02501563, 100.        ,  58.40990039])

In [14]:
for i in range(len(names)):
    print("{}的最终评分为{}".format(names[i], Score[i]))

中信的最终评分为49.70763422811035
光大的最终评分为4.025015628082672
浦发的最终评分为100.0
招商的最终评分为58.409900390756505
